package pl.idzikdev.SmartQuiz.models;

public enum Category {
    FIZYKA, MATEMATYKA, GEOGRAFIA, BIOLOGIA, CHEMIA, INFORMATYKA,
    HISTORIA, MUZYKA, WIEDZA_WSPÓŁCZESNA, MEDYCYNA, TECHNOLOGIA, SZTUKA,
    SPORT
}
